<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class LGATableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('local_government_areas')->truncate();

        $lgas = [

            ['lga' => 'Aba North', 'state' => 1, 'added_by' => 1],
            ['lga' => 'Aba South', 'state' => 1, 'added_by' => 1],
            ['lga' => 'Arochukwu', 'state' => 1, 'added_by' => 1],
            ['lga' => 'Bende', 'state' => 1, 'added_by' => 1],
            ['lga' => 'Ikwuano', 'state' => 1, 'added_by' => 1],
            ['lga' => 'Isiala Ngwa North', 'state' => 1, 'added_by' => 1],
            ['lga' => 'Isiala Ngwa South', 'state' => 1, 'added_by' => 1],
            ['lga' => 'Obingwa', 'state' => 1, 'added_by' => 1],
            ['lga' => 'Ohafia', 'state' => 1, 'added_by' => 1],
            ['lga' => 'Osisioma Ngwa', 'state' => 1, 'added_by' => 1],
            ['lga' => 'Ugwunagbo', 'state' => 1, 'added_by' => 1],
            ['lga' => 'Ukwa East', 'state' => 1, 'added_by' => 1],
            ['lga' => 'Ukwa West', 'state' => 1, 'added_by' => 1],
            ['lga' => 'Umuneochi', 'state' => 1, 'added_by' => 1],
            ['lga' => 'Umuahia North', 'state' => 1, 'added_by' => 1],
            ['lga' => 'Umuahia South', 'state' => 1, 'added_by' => 1],

            ['lga' => 'Demsa', 'state' => 2, 'added_by' => 1],
            ['lga' => 'Fufore', 'state' => 2, 'added_by' => 1],
            ['lga' => 'Ganye', 'state' => 2, 'added_by' => 1],
            ['lga' => 'Girei', 'state' => 2, 'added_by' => 1],
            ['lga' => 'Gombi', 'state' => 2, 'added_by' => 1],
            ['lga' => 'Guyuk', 'state' => 2, 'added_by' => 1],
            ['lga' => 'Hong', 'state' => 2, 'added_by' => 1],
            ['lga' => 'Jada', 'state' => 2, 'added_by' => 1],
            ['lga' => 'Lamurde', 'state' => 2, 'added_by' => 1],
            ['lga' => 'Madagali', 'state' => 2, 'added_by' => 1],
            ['lga' => 'Maiha', 'state' => 2, 'added_by' => 1],
            ['lga' => 'Mayo-Belwa', 'state' => 2, 'added_by' => 1],
            ['lga' => 'Michika', 'state' => 2, 'added_by' => 1],
            ['lga' => 'Mubi North', 'state' => 2, 'added_by' => 1],
            ['lga' => 'Mubi South', 'state' => 2, 'added_by' => 1],
            ['lga' => 'Numan', 'state' => 2, 'added_by' => 1],
            ['lga' => 'Shelleng', 'state' => 2, 'added_by' => 1],
            ['lga' => 'Song', 'state' => 2, 'added_by' => 1],
            ['lga' => 'Toungo', 'state' => 2, 'added_by' => 1],
            ['lga' => 'Yola North', 'state' => 2, 'added_by' => 1],
            ['lga' => 'Yola South', 'state' => 2, 'added_by' => 1],

            ['lga' => 'Abak', 'state' => 3, 'added_by' => 1],
            ['lga' => 'Eastern Obolo', 'state' => 3, 'added_by' => 1],
            ['lga' => 'Eket', 'state' => 3, 'added_by' => 1],
            ['lga' => 'Esit Eket', 'state' => 3, 'added_by' => 1],
            ['lga' => 'Essien Udim', 'state' => 3, 'added_by' => 1],
            ['lga' => 'Ibesikpo Asutan', 'state' => 3, 'added_by' => 1],
            ['lga' => 'Ikono', 'state' => 3, 'added_by' => 1],
            ['lga' => 'Ikot Abasi', 'state' => 3, 'added_by' => 1],
            ['lga' => 'Ikot Ekpene', 'state' => 3, 'added_by' => 1],
            ['lga' => 'Mbo', 'state' => 3, 'added_by' => 1],
            ['lga' => 'Mkpat Enin', 'state' => 3, 'added_by' => 1],
            ['lga' => 'Nsit Atai', 'state' => 3, 'added_by' => 1],
            ['lga' => 'Nsit Ubium', 'state' => 3, 'added_by' => 1],
            ['lga' => 'Obot Akara', 'state' => 3, 'added_by' => 1],
            ['lga' => 'Okobo', 'state' => 3, 'added_by' => 1],
            ['lga' => 'Onna', 'state' => 3, 'added_by' => 1],
            ['lga' => 'Oron', 'state' => 3, 'added_by' => 1],
            ['lga' => 'Oruk Anam', 'state' => 3, 'added_by' => 1],
            ['lga' => 'Udu Uko', 'state' => 3, 'added_by' => 1],
            ['lga' => 'Uyo', 'state' => 3, 'added_by' => 1],
            ['lga' => 'Uruan', 'state' => 3, 'added_by' => 1],

            ['lga' => 'Aguata', 'state' => 4, 'added_by' => 1],
            ['lga' => 'Akwa', 'state' => 4, 'added_by' => 1],
            ['lga' => 'Anambra East', 'state' => 4, 'added_by' => 1],
            ['lga' => 'Anambra West', 'state' => 4, 'added_by' => 1],
            ['lga' => 'Ayamelum', 'state' => 4, 'added_by' => 1],
            ['lga' => 'Awka North', 'state' => 4, 'added_by' => 1],
            ['lga' => 'Awka South', 'state' => 4, 'added_by' => 1],
            ['lga' => 'Dunukofia', 'state' => 4, 'added_by' => 1],
            ['lga' => 'Ekwusigo', 'state' => 4, 'added_by' => 1],
            ['lga' => 'Ihiala', 'state' => 4, 'added_by' => 1],
            ['lga' => 'Idemili North', 'state' => 4, 'added_by' => 1],
            ['lga' => 'Idemili South', 'state' => 4, 'added_by' => 1],
            ['lga' => 'Ihembosi', 'state' => 4, 'added_by' => 1],
            ['lga' => 'Njikoka', 'state' => 4, 'added_by' => 1],
            ['lga' => 'Nnewi', 'state' => 4, 'added_by' => 1],
            ['lga' => 'Nnewi North', 'state' => 4, 'added_by' => 1],
            ['lga' => 'Nnewi South', 'state' => 4, 'added_by' => 1],
            ['lga' => 'Ogbaru', 'state' => 4, 'added_by' => 1],
            ['lga' => 'Onitsha North', 'state' => 4, 'added_by' => 1],
            ['lga' => 'Onitsha South', 'state' => 4, 'added_by' => 1],
            ['lga' => 'Orumba North', 'state' => 4, 'added_by' => 1],
            ['lga' => 'Orumba South', 'state' => 4, 'added_by' => 1],
            ['lga' => 'Oyi', 'state' => 4, 'added_by' => 1],
            ['lga' => 'Uzo Uwani', 'state' => 4, 'added_by' => 1],

            ['lga' => 'Alkaleri', 'state' => 5, 'added_by' => 1],
            ['lga' => 'Bauchi', 'state' => 5, 'added_by' => 1],
            ['lga' => 'Bogoro', 'state' => 5, 'added_by' => 1],
            ['lga' => 'Dass', 'state' => 5, 'added_by' => 1],
            ['lga' => 'Gamawa', 'state' => 5, 'added_by' => 1],
            ['lga' => 'Ganjuwa', 'state' => 5, 'added_by' => 1],
            ['lga' => 'Katagum', 'state' => 5, 'added_by' => 1],
            ['lga' => 'Ningi', 'state' => 5, 'added_by' => 1],
            ['lga' => 'Shira', 'state' => 5, 'added_by' => 1],
            ['lga' => 'Tafawa Balewa', 'state' => 5, 'added_by' => 1],
            ['lga' => 'Toro', 'state' => 5, 'added_by' => 1],
            ['lga' => 'Warji', 'state' => 5, 'added_by' => 1],
            ['lga' => 'Zaki', 'state' => 5, 'added_by' => 1],

            ['lga' => 'Brass', 'state' => 6, 'added_by' => 1],
            ['lga' => 'Ekeremor', 'state' => 6, 'added_by' => 1],
            ['lga' => 'Ekiti', 'state' => 6, 'added_by' => 1],
            ['lga' => 'Kolokuma/Opokuma', 'state' => 6, 'added_by' => 1],
            ['lga' => 'Nembe', 'state' => 6, 'added_by' => 1],
            ['lga' => 'Ogbia', 'state' => 6, 'added_by' => 1],
            ['lga' => 'Sagbama', 'state' => 6, 'added_by' => 1],
            ['lga' => 'Southern Ijaw', 'state' => 6, 'added_by' => 1],
            ['lga' => 'Yenagoa', 'state' => 6, 'added_by' => 1],

            ['lga' => 'Ado', 'state' => 7, 'added_by' => 1],
            ['lga' => 'Agatu', 'state' => 7, 'added_by' => 1],
            ['lga' => 'Apa', 'state' => 7, 'added_by' => 1],
            ['lga' => 'Buruku', 'state' => 7, 'added_by' => 1],
            ['lga' => 'Gboko', 'state' => 7, 'added_by' => 1],
            ['lga' => 'Guma', 'state' => 7, 'added_by' => 1],
            ['lga' => 'Gwer East', 'state' => 7, 'added_by' => 1],
            ['lga' => 'Gwer West', 'state' => 7, 'added_by' => 1],
            ['lga' => 'Katsina-Ala', 'state' => 7, 'added_by' => 1],
            ['lga' => 'Konshisha', 'state' => 7, 'added_by' => 1],
            ['lga' => 'Makurdi', 'state' => 7, 'added_by' => 1],
            ['lga' => 'Ogbadibo', 'state' => 7, 'added_by' => 1],
            ['lga' => 'Okpokwu', 'state' => 7, 'added_by' => 1],
            ['lga' => 'Otukpo', 'state' => 7, 'added_by' => 1],
            ['lga' => 'Ohimini', 'state' => 7, 'added_by' => 1],
            ['lga' => 'Tarka', 'state' => 7, 'added_by' => 1],
            ['lga' => 'Ukum', 'state' => 7, 'added_by' => 1],
            ['lga' => 'Vandeikya', 'state' => 7, 'added_by' => 1],

            ['lga' => 'Abadam', 'state' => 8, 'added_by' => 1],
            ['lga' => 'Bama', 'state' => 8, 'added_by' => 1],
            ['lga' => 'Bayo', 'state' => 8, 'added_by' => 1],
            ['lga' => 'Biu', 'state' => 8, 'added_by' => 1],
            ['lga' => 'Chibok', 'state' => 8, 'added_by' => 1],
            ['lga' => 'Damboa', 'state' => 8, 'added_by' => 1],
            ['lga' => 'Dikwa', 'state' => 8, 'added_by' => 1],
            ['lga' => 'Gubio', 'state' => 8, 'added_by' => 1],
            ['lga' => 'Guzamala', 'state' => 8, 'added_by' => 1],
            ['lga' => 'Hawul', 'state' => 8, 'added_by' => 1],
            ['lga' => 'Jere', 'state' => 8, 'added_by' => 1],
            ['lga' => 'Kaga', 'state' => 8, 'added_by' => 1],
            ['lga' => 'Kala Balge', 'state' => 8, 'added_by' => 1],
            ['lga' => 'Konduga', 'state' => 8, 'added_by' => 1],
            ['lga' => 'Mafa', 'state' => 8, 'added_by' => 1],
            ['lga' => 'Magumeri', 'state' => 8, 'added_by' => 1],
            ['lga' => 'Maiduguri', 'state' => 8, 'added_by' => 1],
            ['lga' => 'Ngala', 'state' => 8, 'added_by' => 1],
            ['lga' => 'Nganzai', 'state' => 8, 'added_by' => 1],
            ['lga' => 'Shani', 'state' => 8, 'added_by' => 1],

            ['lga' => 'Abi', 'state' => 9, 'added_by' => 1],
            ['lga' => 'Akampa', 'state' => 9, 'added_by' => 1],
            ['lga' => 'Bakassi', 'state' => 9, 'added_by' => 1],
            ['lga' => 'Biase', 'state' => 9, 'added_by' => 1],
            ['lga' => 'Boki', 'state' => 9, 'added_by' => 1],
            ['lga' => 'Calabar Municipal', 'state' => 9, 'added_by' => 1],
            ['lga' => 'Calabar South', 'state' => 9, 'added_by' => 1],
            ['lga' => 'Ekureku', 'state' => 9, 'added_by' => 1],
            ['lga' => 'Ikom', 'state' => 9, 'added_by' => 1],
            ['lga' => 'Obanliku', 'state' => 9, 'added_by' => 1],
            ['lga' => 'Obubra', 'state' => 9, 'added_by' => 1],
            ['lga' => 'Odukpani', 'state' => 9, 'added_by' => 1],
            ['lga' => 'Okpoku', 'state' => 9, 'added_by' => 1],
            ['lga' => 'Yala', 'state' => 9, 'added_by' => 1],

            ['lga' => 'Aniocha North', 'state' => 10, 'added_by' => 1],
            ['lga' => 'Aniocha South', 'state' => 10, 'added_by' => 1],
            ['lga' => 'Bomadi', 'state' => 10, 'added_by' => 1],
            ['lga' => 'Burutu', 'state' => 10, 'added_by' => 1],
            ['lga' => 'Ethiope East', 'state' => 10, 'added_by' => 1],
            ['lga' => 'Ethiope West', 'state' => 10, 'added_by' => 1],
            ['lga' => 'Ika North East', 'state' => 10, 'added_by' => 1],
            ['lga' => 'Ika South', 'state' => 10, 'added_by' => 1],
            ['lga' => 'Isoko North', 'state' => 10, 'added_by' => 1],
            ['lga' => 'Isoko South', 'state' => 10, 'added_by' => 1],
            ['lga' => 'Ndokwa East', 'state' => 10, 'added_by' => 1],
            ['lga' => 'Ndokwa West', 'state' => 10, 'added_by' => 1],
            ['lga' => 'Okpe', 'state' => 10, 'added_by' => 1],
            ['lga' => 'Oshimili North', 'state' => 10, 'added_by' => 1],
            ['lga' => 'Oshimili South', 'state' => 10, 'added_by' => 1],
            ['lga' => 'Patani', 'state' => 10, 'added_by' => 1],
            ['lga' => 'Sapele', 'state' => 10, 'added_by' => 1],
            ['lga' => 'Udu', 'state' => 10, 'added_by' => 1],
            ['lga' => 'Ughelli North', 'state' => 10, 'added_by' => 1],
            ['lga' => 'Ughelli South', 'state' => 10, 'added_by' => 1],
            ['lga' => 'Warri North', 'state' => 10, 'added_by' => 1],
            ['lga' => 'Warri South', 'state' => 10, 'added_by' => 1],
            ['lga' => 'Warri South West', 'state' => 10, 'added_by' => 1],

            ['lga' => 'Abakaliki', 'state' => 11, 'added_by' => 1],
            ['lga' => 'Afikpo North', 'state' => 11, 'added_by' => 1],
            ['lga' => 'Afikpo South', 'state' => 11, 'added_by' => 1],
            ['lga' => 'Ebonyi', 'state' => 11, 'added_by' => 1],
            ['lga' => 'Ezza North', 'state' => 11, 'added_by' => 1],
            ['lga' => 'Ezza South', 'state' => 11, 'added_by' => 1],
            ['lga' => 'Ikwo', 'state' => 11, 'added_by' => 1],
            ['lga' => 'Ishielu', 'state' => 11, 'added_by' => 1],
            ['lga' => 'Ohaozara', 'state' => 11, 'added_by' => 1],
            ['lga' => 'Ohaukwu', 'state' => 11, 'added_by' => 1],
            ['lga' => 'Onicha', 'state' => 11, 'added_by' => 1],
            ['lga' => 'Izzi', 'state' => 11, 'added_by' => 1],

            ['lga' => 'Akoko-Edo', 'state' => 12, 'added_by' => 1],
            ['lga' => 'Esan Central', 'state' => 12, 'added_by' => 1],
            ['lga' => 'Esan North-East', 'state' => 12, 'added_by' => 1],
            ['lga' => 'Esan South-East', 'state' => 12, 'added_by' => 1],
            ['lga' => 'Etsako Central', 'state' => 12, 'added_by' => 1],
            ['lga' => 'Etsako East', 'state' => 12, 'added_by' => 1],
            ['lga' => 'Etsako West', 'state' => 12, 'added_by' => 1],
            ['lga' => 'Igueben', 'state' => 12, 'added_by' => 1],
            ['lga' => 'Ikpoba-Okha', 'state' => 12, 'added_by' => 1],
            ['lga' => 'Oredo', 'state' => 12, 'added_by' => 1],
            ['lga' => 'Orhionmwon', 'state' => 12, 'added_by' => 1],
            ['lga' => 'Ovia North-East', 'state' => 12, 'added_by' => 1],
            ['lga' => 'Ovia South-West', 'state' => 12, 'added_by' => 1],
            ['lga' => 'Uhunmwonde', 'state' => 12, 'added_by' => 1],
            ['lga' => 'Egor', 'state' => 12, 'added_by' => 1],

            ['lga' => 'Ado-Ekiti', 'state' => 13, 'added_by' => 1],
            ['lga' => 'Ekiti East', 'state' => 13, 'added_by' => 1],
            ['lga' => 'Ekiti South-West', 'state' => 13, 'added_by' => 1],
            ['lga' => 'Ekiti West', 'state' => 13, 'added_by' => 1],
            ['lga' => 'Irepodun/Ifelodun', 'state' => 13, 'added_by' => 1],
            ['lga' => 'Ise/Orun', 'state' => 13, 'added_by' => 1],
            ['lga' => 'Moba', 'state' => 13, 'added_by' => 1],
            ['lga' => 'Oye', 'state' => 13, 'added_by' => 1],
            ['lga' => 'Gboyin', 'state' => 13, 'added_by' => 1],
            ['lga' => 'Emure', 'state' => 13, 'added_by' => 1],
            ['lga' => 'Ikere', 'state' => 13, 'added_by' => 1],
            ['lga' => 'Ikole', 'state' => 13, 'added_by' => 1],
            ['lga' => 'Efon', 'state' => 13, 'added_by' => 1],
            ['lga' => 'Aiyekire', 'state' => 13, 'added_by' => 1],
            ['lga' => 'Ekiti South-East', 'state' => 13, 'added_by' => 1],
            ['lga' => 'Ekitit North', 'state' => 13, 'added_by' => 1],

            ['lga' => 'Enugu East', 'state' => 14, 'added_by' => 1],
            ['lga' => 'Enugu North', 'state' => 14, 'added_by' => 1],
            ['lga' => 'Enugu South', 'state' => 14, 'added_by' => 1],
            ['lga' => 'Nsukka', 'state' => 14, 'added_by' => 1],
            ['lga' => 'Oji River', 'state' => 14, 'added_by' => 1],
            ['lga' => 'Udenu', 'state' => 14, 'added_by' => 1],
            ['lga' => 'Udi', 'state' => 14, 'added_by' => 1],
            ['lga' => 'Igbo Etiti', 'state' => 14, 'added_by' => 1],
            ['lga' => 'Igbo Eze North', 'state' => 14, 'added_by' => 1],
            ['lga' => 'Igbo Eze South', 'state' => 14, 'added_by' => 1],
            ['lga' => 'Awgu', 'state' => 14, 'added_by' => 1],
            ['lga' => 'Ezeagu', 'state' => 14, 'added_by' => 1],
            ['lga' => 'Enugu West', 'state' => 14, 'added_by' => 1],

            ['lga' => 'Akko', 'state' => 15, 'added_by' => 1],
            ['lga' => 'Balanga', 'state' => 15, 'added_by' => 1],
            ['lga' => 'Billiri', 'state' => 15, 'added_by' => 1],
            ['lga' => 'Dukku', 'state' => 15, 'added_by' => 1],
            ['lga' => 'Gombe', 'state' => 15, 'added_by' => 1],
            ['lga' => 'Kaltungo', 'state' => 15, 'added_by' => 1],
            ['lga' => 'Kwami', 'state' => 15, 'added_by' => 1],
            ['lga' => 'Nafada', 'state' => 15, 'added_by' => 1],
            ['lga' => 'Shongom', 'state' => 15, 'added_by' => 1],
            ['lga' => 'Yamaltu/Deba', 'state' => 15, 'added_by' => 1],

            ['lga' => 'Aboh Mbaise', 'state' => 16, 'added_by' => 1],
            ['lga' => 'Ahiazu Mbaise', 'state' => 16, 'added_by' => 1],
            ['lga' => 'Ekiti', 'state' => 16, 'added_by' => 1],
            ['lga' => 'Ehime Mbano', 'state' => 16, 'added_by' => 1],
            ['lga' => 'Ezinihitte', 'state' => 16, 'added_by' => 1],
            ['lga' => 'Ihitte/Uboma', 'state' => 16, 'added_by' => 1],
            ['lga' => 'Ikeduru', 'state' => 16, 'added_by' => 1],
            ['lga' => 'Isu', 'state' => 16, 'added_by' => 1],
            ['lga' => 'Mbaitoli', 'state' => 16, 'added_by' => 1],
            ['lga' => 'Ngor Okpala', 'state' => 16, 'added_by' => 1],
            ['lga' => 'Nkwerre', 'state' => 16, 'added_by' => 1],
            ['lga' => 'Nwangele', 'state' => 16, 'added_by' => 1],
            ['lga' => 'Obowo', 'state' => 16, 'added_by' => 1],
            ['lga' => 'Oguta', 'state' => 16, 'added_by' => 1],
            ['lga' => 'Ohaji/Egbema', 'state' => 16, 'added_by' => 1],
            ['lga' => 'Orlu', 'state' => 16, 'added_by' => 1],
            ['lga' => 'Orsu', 'state' => 16, 'added_by' => 1],
            ['lga' => 'Owerri Municipal', 'state' => 16, 'added_by' => 1],
            ['lga' => 'Owerri West', 'state' => 16, 'added_by' => 1],
            ['lga' => 'Owerri North', 'state' => 16, 'added_by' => 1],
            ['lga' => 'Isiala Mbano', 'state' => 16, 'added_by' => 1],
            ['lga' => 'Okigwe', 'state' => 16, 'added_by' => 1],

            ['lga' => 'Auyo', 'state' => 17, 'added_by' => 1],
            ['lga' => 'Babura', 'state' => 17, 'added_by' => 1],
            ['lga' => 'Birin Kudu', 'state' => 17, 'added_by' => 1],
            ['lga' => 'Dutse', 'state' => 17, 'added_by' => 1],
            ['lga' => 'Dukku', 'state' => 17, 'added_by' => 1],
            ['lga' => 'Gagarawa', 'state' => 17, 'added_by' => 1],
            ['lga' => 'Gumel', 'state' => 17, 'added_by' => 1],
            ['lga' => 'Hadejia', 'state' => 17, 'added_by' => 1],
            ['lga' => 'Jahun', 'state' => 17, 'added_by' => 1],
            ['lga' => 'Kazaure', 'state' => 17, 'added_by' => 1],
            ['lga' => 'Kiri Kasama', 'state' => 17, 'added_by' => 1],
            ['lga' => 'Maigatari', 'state' => 17, 'added_by' => 1],
            ['lga' => 'Malam Madori', 'state' => 17, 'added_by' => 1],
            ['lga' => 'Miga', 'state' => 17, 'added_by' => 1],
            ['lga' => 'Ringim', 'state' => 17, 'added_by' => 1],
            ['lga' => 'Sule Tankarkar', 'state' => 17, 'added_by' => 1],
            ['lga' => 'Yankwashi', 'state' => 17, 'added_by' => 1],
            ['lga' => 'Guri', 'state' => 17, 'added_by' => 1],
            ['lga' => 'Kaugama', 'state' => 17, 'added_by' => 1],

            ['lga' => 'Birnin Gwari', 'state' => 18, 'added_by' => 1],
            ['lga' => 'Chikun', 'state' => 18, 'added_by' => 1],
            ['lga' => 'Giwa', 'state' => 18, 'added_by' => 1],
            ['lga' => 'Igabi', 'state' => 18, 'added_by' => 1],
            ['lga' => 'Jaba', 'state' => 18, 'added_by' => 1],
            ['lga' => 'Jema\'a', 'state' => 18, 'added_by' => 1],
            ['lga' => 'Kachia', 'state' => 18, 'added_by' => 1],
            ['lga' => 'Kaduna North', 'state' => 18, 'added_by' => 1],
            ['lga' => 'Kaduna South', 'state' => 18, 'added_by' => 1],
            ['lga' => 'Kagarko', 'state' => 18, 'added_by' => 1],
            ['lga' => 'Kajuru', 'state' => 18, 'added_by' => 1],
            ['lga' => 'Kaura', 'state' => 18, 'added_by' => 1],
            ['lga' => 'Kauru', 'state' => 18, 'added_by' => 1],
            ['lga' => 'Lere', 'state' => 18, 'added_by' => 1],
            ['lga' => 'Sanga', 'state' => 18, 'added_by' => 1],
            ['lga' => 'Zangon Kataf', 'state' => 18, 'added_by' => 1],
            ['lga' => 'Makarfi', 'state' => 18, 'added_by' => 1],
            ['lga' => 'Sabon Gari', 'state' => 18, 'added_by' => 1],
            ['lga' => 'Soba', 'state' => 18, 'added_by' => 1],
            ['lga' => 'Kudan', 'state' => 18, 'added_by' => 1],
            ['lga' => 'Ikara', 'state' => 18, 'added_by' => 1],
            ['lga' => 'Zaria', 'state' => 18, 'added_by' => 1],

            ['lga' => 'Ajingi', 'state' => 19, 'added_by' => 1],
            ['lga' => 'Albasu', 'state' => 19, 'added_by' => 1],
            ['lga' => 'Bagwai', 'state' => 19, 'added_by' => 1],
            ['lga' => 'Bebeji', 'state' => 19, 'added_by' => 1],
            ['lga' => 'Bichi', 'state' => 19, 'added_by' => 1],
            ['lga' => 'Birnin Kudu', 'state' => 19, 'added_by' => 1],
            ['lga' => 'Dala', 'state' => 19, 'added_by' => 1],
            ['lga' => 'Dawakin Tofa', 'state' => 19, 'added_by' => 1],
            ['lga' => 'Doguwa', 'state' => 19, 'added_by' => 1],
            ['lga' => 'Gaya', 'state' => 19, 'added_by' => 1],
            ['lga' => 'Gezawa', 'state' => 19, 'added_by' => 1],
            ['lga' => 'Gwarzo', 'state' => 19, 'added_by' => 1],
            ['lga' => 'Kabo', 'state' => 19, 'added_by' => 1],
            ['lga' => 'Kano', 'state' => 19, 'added_by' => 1],
            ['lga' => 'Karaye', 'state' => 19, 'added_by' => 1],
            ['lga' => 'Kibiya', 'state' => 19, 'added_by' => 1],
            ['lga' => 'Kumbotso', 'state' => 19, 'added_by' => 1],
            ['lga' => 'Madobi', 'state' => 19, 'added_by' => 1],
            ['lga' => 'Makoda', 'state' => 19, 'added_by' => 1],
            ['lga' => 'Maqadasi', 'state' => 19, 'added_by' => 1],
            ['lga' => 'Minjibir', 'state' => 19, 'added_by' => 1],
            ['lga' => 'Nasarawa', 'state' => 19, 'added_by' => 1],
            ['lga' => 'Rano', 'state' => 19, 'added_by' => 1],
            ['lga' => 'Tarauni', 'state' => 19, 'added_by' => 1],
            ['lga' => 'Tofa', 'state' => 19, 'added_by' => 1],
            ['lga' => 'Tsanyawa', 'state' => 19, 'added_by' => 1],
            ['lga' => 'Ungogo', 'state' => 19, 'added_by' => 1],
            ['lga' => 'Warawa', 'state' => 19, 'added_by' => 1],
            ['lga' => 'Wudil', 'state' => 19, 'added_by' => 1],

            ['lga' => 'Bakori', 'state' => 20, 'added_by' => 1],
            ['lga' => 'Batagarawa', 'state' => 20, 'added_by' => 1],
            ['lga' => 'Batsari', 'state' => 20, 'added_by' => 1],
            ['lga' => 'Baure', 'state' => 20, 'added_by' => 1],
            ['lga' => 'Chadi', 'state' => 20, 'added_by' => 1],
            ['lga' => 'Dandume', 'state' => 20, 'added_by' => 1],
            ['lga' => 'Danja', 'state' => 20, 'added_by' => 1],
            ['lga' => 'Dutsi', 'state' => 20, 'added_by' => 1],
            ['lga' => 'Funtua', 'state' => 20, 'added_by' => 1],
            ['lga' => 'Ingawa', 'state' => 20, 'added_by' => 1],
            ['lga' => 'Kafur', 'state' => 20, 'added_by' => 1],
            ['lga' => 'Kaita', 'state' => 20, 'added_by' => 1],
            ['lga' => 'Katsina', 'state' => 20, 'added_by' => 1],
            ['lga' => 'Malumfashi', 'state' => 20, 'added_by' => 1],
            ['lga' => 'Mashi', 'state' => 20, 'added_by' => 1],
            ['lga' => 'Rimi', 'state' => 20, 'added_by' => 1],
            ['lga' => 'Sabuwa', 'state' => 20, 'added_by' => 1],
            ['lga' => 'Sandamu', 'state' => 20, 'added_by' => 1],
            ['lga' => 'Zango', 'state' => 20, 'added_by' => 1],

            ['lga' => 'Aleiro', 'state' => 21, 'added_by' => 1],
            ['lga' => 'Arewa Dandi', 'state' => 21, 'added_by' => 1],
            ['lga' => 'Argungu', 'state' => 21, 'added_by' => 1],
            ['lga' => 'Bagudo', 'state' => 21, 'added_by' => 1],
            ['lga' => 'Birnin Kebbi', 'state' => 21, 'added_by' => 1],
            ['lga' => 'Bunza', 'state' => 21, 'added_by' => 1],
            ['lga' => 'Dandi', 'state' => 21, 'added_by' => 1],
            ['lga' => 'Fakai', 'state' => 21, 'added_by' => 1],
            ['lga' => 'Gwandu', 'state' => 21, 'added_by' => 1],
            ['lga' => 'Jega', 'state' => 21, 'added_by' => 1],
            ['lga' => 'Kalgo', 'state' => 21, 'added_by' => 1],
            ['lga' => 'Koko/Besse', 'state' => 21, 'added_by' => 1],
            ['lga' => 'Maiyama', 'state' => 21, 'added_by' => 1],
            ['lga' => 'Ngaski', 'state' => 21, 'added_by' => 1],
            ['lga' => 'Shanga', 'state' => 21, 'added_by' => 1],
            ['lga' => 'Suru', 'state' => 21, 'added_by' => 1],
            ['lga' => 'Zuru', 'state' => 21, 'added_by' => 1],

            ['lga' => 'Adavi', 'state' => 22, 'added_by' => 1],
            ['lga' => 'Ajaokuta', 'state' => 22, 'added_by' => 1],
            ['lga' => 'Ankpa', 'state' => 22, 'added_by' => 1],
            ['lga' => 'Bassa', 'state' => 22, 'added_by' => 1],
            ['lga' => 'Dekina', 'state' => 22, 'added_by' => 1],
            ['lga' => 'Ibaji', 'state' => 22, 'added_by' => 1],
            ['lga' => 'Idah', 'state' => 22, 'added_by' => 1],
            ['lga' => 'Igalamela-Odolu', 'state' => 22, 'added_by' => 1],
            ['lga' => 'Kabba/Bunu', 'state' => 22, 'added_by' => 1],
            ['lga' => 'Kogi', 'state' => 22, 'added_by' => 1],
            ['lga' => 'Lokoja', 'state' => 22, 'added_by' => 1],
            ['lga' => 'Mopa-Muro', 'state' => 22, 'added_by' => 1],
            ['lga' => 'Ofu', 'state' => 22, 'added_by' => 1],
            ['lga' => 'Ogori/Mangongo', 'state' => 22, 'added_by' => 1],
            ['lga' => 'Okene', 'state' => 22, 'added_by' => 1],
            ['lga' => 'Okehi', 'state' => 22, 'added_by' => 1],
            ['lga' => 'Okoro-Gbede', 'state' => 22, 'added_by' => 1],
            ['lga' => 'Yagba East', 'state' => 22, 'added_by' => 1],
            ['lga' => 'Yagba West', 'state' => 22, 'added_by' => 1],

            ['lga' => 'Asa', 'state' => 23, 'added_by' => 1],
            ['lga' => 'Baruten', 'state' => 23, 'added_by' => 1],
            ['lga' => 'Ekiti', 'state' => 23, 'added_by' => 1],
            ['lga' => 'Ilorin East', 'state' => 23, 'added_by' => 1],
            ['lga' => 'Ilorin South', 'state' => 23, 'added_by' => 1],
            ['lga' => 'Ilorin West', 'state' => 23, 'added_by' => 1],
            ['lga' => 'Irepodun', 'state' => 23, 'added_by' => 1],
            ['lga' => 'Isin', 'state' => 23, 'added_by' => 1],
            ['lga' => 'Kaiama', 'state' => 23, 'added_by' => 1],
            ['lga' => 'Moro', 'state' => 23, 'added_by' => 1],
            ['lga' => 'Offa', 'state' => 23, 'added_by' => 1],
            ['lga' => 'Oyun', 'state' => 23, 'added_by' => 1],
            ['lga' => 'Pategi', 'state' => 23, 'added_by' => 1],

            ['lga' => 'Agege', 'state' => 24, 'added_by' => 1],
            ['lga' => 'Ajeromi Ifelodun', 'state' => 24, 'added_by' => 1],
            ['lga' => 'Alimosho', 'state' => 24, 'added_by' => 1],
            ['lga' => 'Apapa', 'state' => 24, 'added_by' => 1],
            ['lga' => 'Badagry', 'state' => 24, 'added_by' => 1],
            ['lga' => 'Bakoko', 'state' => 24, 'added_by' => 1],
            ['lga' => 'Epe', 'state' => 24, 'added_by' => 1],
            ['lga' => 'Eti Osa', 'state' => 24, 'added_by' => 1],
            ['lga' => 'Ibeju Lekki', 'state' => 24, 'added_by' => 1],
            ['lga' => 'Ifako-Ijaiye', 'state' => 24, 'added_by' => 1],
            ['lga' => 'Ikeja', 'state' => 24, 'added_by' => 1],
            ['lga' => 'Ikorodu', 'state' => 24, 'added_by' => 1],
            ['lga' => 'Kosofe', 'state' => 24, 'added_by' => 1],
            ['lga' => 'Lagos Island', 'state' => 24, 'added_by' => 1],
            ['lga' => 'Lagos Mainland', 'state' => 24, 'added_by' => 1],
            ['lga' => 'Mushin', 'state' => 24, 'added_by' => 1],
            ['lga' => 'Ojo', 'state' => 24, 'added_by' => 1],
            ['lga' => 'Oshodi-Isolo', 'state' => 24, 'added_by' => 1],
            ['lga' => 'Shomolu', 'state' => 24, 'added_by' => 1],
            ['lga' => 'Surulere', 'state' => 24, 'added_by' => 1],

            ['lga' => 'Akwanga', 'state' => 25, 'added_by' => 1],
            ['lga' => 'Doma', 'state' => 25, 'added_by' => 1],
            ['lga' => 'Karshi', 'state' => 25, 'added_by' => 1],
            ['lga' => 'Keana', 'state' => 25, 'added_by' => 1],
            ['lga' => 'Keffi', 'state' => 25, 'added_by' => 1],
            ['lga' => 'Lafia', 'state' => 25, 'added_by' => 1],
            ['lga' => 'Nasarawa', 'state' => 25, 'added_by' => 1],
            ['lga' => 'Obi', 'state' => 25, 'added_by' => 1],
            ['lga' => 'Toto', 'state' => 25, 'added_by' => 1],
            ['lga' => 'Wamba', 'state' => 25, 'added_by' => 1],
            ['lga' => 'Awe', 'state' => 25, 'added_by' => 1],

            ['lga' => 'Agwara', 'state' => 26, 'added_by' => 1],
            ['lga' => 'Bida', 'state' => 26, 'added_by' => 1],
            ['lga' => 'Borgu', 'state' => 26, 'added_by' => 1],
            ['lga' => 'Bosso', 'state' => 26, 'added_by' => 1],
            ['lga' => 'Chanchaga', 'state' => 26, 'added_by' => 1],
            ['lga' => 'Edati', 'state' => 26, 'added_by' => 1],
            ['lga' => 'Gurara', 'state' => 26, 'added_by' => 1],
            ['lga' => 'Katcha', 'state' => 26, 'added_by' => 1],
            ['lga' => 'Lavun', 'state' => 26, 'added_by' => 1],
            ['lga' => 'Mokwa', 'state' => 26, 'added_by' => 1],
            ['lga' => 'Rafi', 'state' => 26, 'added_by' => 1],
            ['lga' => 'Shiroro', 'state' => 26, 'added_by' => 1],
            ['lga' => 'Suleja', 'state' => 26, 'added_by' => 1],
            ['lga' => 'Tafa', 'state' => 26, 'added_by' => 1],
            ['lga' => 'Wushishi', 'state' => 26, 'added_by' => 1],

            ['lga' => 'Abeokuta North', 'state' => 27, 'added_by' => 1],
            ['lga' => 'Abeokuta South', 'state' => 27, 'added_by' => 1],
            ['lga' => 'Ado-Odo/Ota', 'state' => 27, 'added_by' => 1],
            ['lga' => 'Ewekoro', 'state' => 27, 'added_by' => 1],
            ['lga' => 'Ifo', 'state' => 27, 'added_by' => 1],
            ['lga' => 'Ijebu East', 'state' => 27, 'added_by' => 1],
            ['lga' => 'Ijebu North', 'state' => 27, 'added_by' => 1],
            ['lga' => 'Ijebu Ode', 'state' => 27, 'added_by' => 1],
            ['lga' => 'Ogun Waterside', 'state' => 27, 'added_by' => 1],
            ['lga' => 'Remo North', 'state' => 27, 'added_by' => 1],
            ['lga' => 'Sagamu', 'state' => 27, 'added_by' => 1],
            ['lga' => 'Yewa North', 'state' => 27, 'added_by' => 1],
            ['lga' => 'Yewa South', 'state' => 27, 'added_by' => 1],
            ['lga' => 'Obafemi-Owode', 'state' => 27, 'added_by' => 1],
            ['lga' => 'Odeda', 'state' => 27, 'added_by' => 1],
            ['lga' => 'Odogbolu', 'state' => 27, 'added_by' => 1],
            ['lga' => 'Ikenne', 'state' => 27, 'added_by' => 1],
            ['lga' => 'Ayetoro', 'state' => 27, 'added_by' => 1],

            ['lga' => 'Akoko North-East', 'state' => 28, 'added_by' => 1],
            ['lga' => 'Akoko North-West', 'state' => 28, 'added_by' => 1],
            ['lga' => 'Akoko South-East', 'state' => 28, 'added_by' => 1],
            ['lga' => 'Akoko South-West', 'state' => 28, 'added_by' => 1],
            ['lga' => 'Akure North', 'state' => 28, 'added_by' => 1],
            ['lga' => 'Akure South', 'state' => 28, 'added_by' => 1],
            ['lga' => 'Ese Odo', 'state' => 28, 'added_by' => 1],
            ['lga' => 'Idanre', 'state' => 28, 'added_by' => 1],
            ['lga' => 'Ifedore', 'state' => 28, 'added_by' => 1],
            ['lga' => 'Ile Oluji/Okeigbo', 'state' => 28, 'added_by' => 1],
            ['lga' => 'Odigbo', 'state' => 28, 'added_by' => 1],
            ['lga' => 'Ondo East', 'state' => 28, 'added_by' => 1],
            ['lga' => 'Ondo West', 'state' => 28, 'added_by' => 1],
            ['lga' => 'Ose', 'state' => 28, 'added_by' => 1],
            ['lga' => 'Owo', 'state' => 28, 'added_by' => 1],
            ['lga' => 'Ilaje', 'state' => 28, 'added_by' => 1],
            ['lga' => 'Irele', 'state' => 28, 'added_by' => 1],

            ['lga' => 'Aiyedaade', 'state' => 29, 'added_by' => 1],
            ['lga' => 'Aiyedade', 'state' => 29, 'added_by' => 1],
            ['lga' => 'Boluwaduro', 'state' => 29, 'added_by' => 1],
            ['lga' => 'Boripe', 'state' => 29, 'added_by' => 1],
            ['lga' => 'Ede North', 'state' => 29, 'added_by' => 1],
            ['lga' => 'Ede South', 'state' => 29, 'added_by' => 1],
            ['lga' => 'Egbedore', 'state' => 29, 'added_by' => 1],
            ['lga' => 'Ife East', 'state' => 29, 'added_by' => 1],
            ['lga' => 'Ife North', 'state' => 29, 'added_by' => 1],
            ['lga' => 'Ife South', 'state' => 29, 'added_by' => 1],
            ['lga' => 'Ifedayo', 'state' => 29, 'added_by' => 1],
            ['lga' => 'Ifelodun', 'state' => 29, 'added_by' => 1],
            ['lga' => 'Ilesa East', 'state' => 29, 'added_by' => 1],
            ['lga' => 'Ilesa West', 'state' => 29, 'added_by' => 1],
            ['lga' => 'Isokan', 'state' => 29, 'added_by' => 1],
            ['lga' => 'Iwo', 'state' => 29, 'added_by' => 1],
            ['lga' => 'Obokun', 'state' => 29, 'added_by' => 1],
            ['lga' => 'Odo Otin', 'state' => 29, 'added_by' => 1],
            ['lga' => 'Osogbo', 'state' => 29, 'added_by' => 1],
            ['lga' => 'Atakunmosa East', 'state' => 29, 'added_by' => 1],
            ['lga' => 'Atakunmosa West', 'state' => 29, 'added_by' => 1],
            ['lga' => 'Ola Oluwa', 'state' => 29, 'added_by' => 1],
            ['lga' => 'Olorunda', 'state' => 29, 'added_by' => 1],

            ['lga' => 'Akinyele', 'state' => 30, 'added_by' => 1],
            ['lga' => 'Afijio', 'state' => 30, 'added_by' => 1],
            ['lga' => 'Atiba', 'state' => 30, 'added_by' => 1],
            ['lga' => 'Atisbo', 'state' => 30, 'added_by' => 1],
            ['lga' => 'Egbeda', 'state' => 30, 'added_by' => 1],
            ['lga' => 'Ibadan North', 'state' => 30, 'added_by' => 1],
            ['lga' => 'Ibadan North-East', 'state' => 30, 'added_by' => 1],
            ['lga' => 'Ibadan North-West', 'state' => 30, 'added_by' => 1],
            ['lga' => 'Ibadan South-East', 'state' => 30, 'added_by' => 1],
            ['lga' => 'Ibadan South-West', 'state' => 30, 'added_by' => 1],
            ['lga' => 'Ibarapa Central', 'state' => 30, 'added_by' => 1],
            ['lga' => 'Ibarapa East', 'state' => 30, 'added_by' => 1],
            ['lga' => 'Ibarapa North', 'state' => 30, 'added_by' => 1],
            ['lga' => 'Ido', 'state' => 30, 'added_by' => 1],
            ['lga' => 'Iseyin', 'state' => 30, 'added_by' => 1],
            ['lga' => 'Itesiwaju', 'state' => 30, 'added_by' => 1],
            ['lga' => 'Ogbomosho North', 'state' => 30, 'added_by' => 1],
            ['lga' => 'Ogbomosho South', 'state' => 30, 'added_by' => 1],
            ['lga' => 'Oyo East', 'state' => 30, 'added_by' => 1],
            ['lga' => 'Oyo West', 'state' => 30, 'added_by' => 1],

            ['lga' => 'Bokkos', 'state' => 31, 'added_by' => 1],
            ['lga' => 'Barkin Ladi', 'state' => 31, 'added_by' => 1],
            ['lga' => 'Bassa', 'state' => 31, 'added_by' => 1],
            ['lga' => 'Jos East', 'state' => 31, 'added_by' => 1],
            ['lga' => 'Jos North', 'state' => 31, 'added_by' => 1],
            ['lga' => 'Jos South', 'state' => 31, 'added_by' => 1],
            ['lga' => 'Kanam', 'state' => 31, 'added_by' => 1],
            ['lga' => 'Kanke', 'state' => 31, 'added_by' => 1],
            ['lga' => 'Langtang North', 'state' => 31, 'added_by' => 1],
            ['lga' => 'Langtang South', 'state' => 31, 'added_by' => 1],
            ['lga' => 'Mangu', 'state' => 31, 'added_by' => 1],
            ['lga' => 'Pankshin', 'state' => 31, 'added_by' => 1],
            ['lga' => 'Riyom', 'state' => 31, 'added_by' => 1],
            ['lga' => 'Shendam', 'state' => 31, 'added_by' => 1],
            ['lga' => 'Wase', 'state' => 31, 'added_by' => 1],

            ['lga' => 'Abua/Odual', 'state' => 32, 'added_by' => 1],
            ['lga' => 'Ahoada East', 'state' => 32, 'added_by' => 1],
            ['lga' => 'Ahoada West', 'state' => 32, 'added_by' => 1],
            ['lga' => 'Akuku-Toru', 'state' => 32, 'added_by' => 1],
            ['lga' => 'Asari-Toru', 'state' => 32, 'added_by' => 1],
            ['lga' => 'Bonny', 'state' => 32, 'added_by' => 1],
            ['lga' => 'Degema', 'state' => 32, 'added_by' => 1],
            ['lga' => 'Emohua', 'state' => 32, 'added_by' => 1],
            ['lga' => 'Etche', 'state' => 32, 'added_by' => 1],
            ['lga' => 'Gokana', 'state' => 32, 'added_by' => 1],
            ['lga' => 'Ikwerre', 'state' => 32, 'added_by' => 1],
            ['lga' => 'Obio-Akpor', 'state' => 32, 'added_by' => 1],
            ['lga' => 'Ogba/Egbema/Ndoni', 'state' => 32, 'added_by' => 1],
            ['lga' => 'Ogu/Bolo', 'state' => 32, 'added_by' => 1],
            ['lga' => 'Okrika', 'state' => 32, 'added_by' => 1],
            ['lga' => 'Oyo', 'state' => 32, 'added_by' => 1],
            ['lga' => 'Port Harcourt', 'state' => 32, 'added_by' => 1],
            ['lga' => 'Tai', 'state' => 32, 'added_by' => 1],
            ['lga' => 'Eleme', 'state' => 32, 'added_by' => 1],
            ['lga' => 'Phalga', 'state' => 32, 'added_by' => 1],

            ['lga' => 'Binji', 'state' => 33, 'added_by' => 1],
            ['lga' => 'Bodinga', 'state' => 33, 'added_by' => 1],
            ['lga' => 'Dange Shuni', 'state' => 33, 'added_by' => 1],
            ['lga' => 'Gada', 'state' => 33, 'added_by' => 1],
            ['lga' => 'Goronyo', 'state' => 33, 'added_by' => 1],
            ['lga' => 'Gudu', 'state' => 33, 'added_by' => 1],
            ['lga' => 'Illela', 'state' => 33, 'added_by' => 1],
            ['lga' => 'Kebbe', 'state' => 33, 'added_by' => 1],
            ['lga' => 'Kware', 'state' => 33, 'added_by' => 1],
            ['lga' => 'Rabah', 'state' => 33, 'added_by' => 1],
            ['lga' => 'Sokoto North', 'state' => 33, 'added_by' => 1],
            ['lga' => 'Sokoto South', 'state' => 33, 'added_by' => 1],
            ['lga' => 'Tambuwal', 'state' => 33, 'added_by' => 1],
            ['lga' => 'Wamako', 'state' => 33, 'added_by' => 1],
            ['lga' => 'Yabo', 'state' => 33, 'added_by' => 1],
            ['lga' => 'Shagari', 'state' => 33, 'added_by' => 1],
            ['lga' => 'Tureta', 'state' => 33, 'added_by' => 1],
            ['lga' => 'Gwadabawa', 'state' => 33, 'added_by' => 1],

            ['lga' => 'Ardo Kola', 'state' => 34, 'added_by' => 1],
            ['lga' => 'Donga', 'state' => 34, 'added_by' => 1],
            ['lga' => 'Gashaka', 'state' => 34, 'added_by' => 1],
            ['lga' => 'Ganjuwa', 'state' => 34, 'added_by' => 1],
            ['lga' => 'Kurmi', 'state' => 34, 'added_by' => 1],
            ['lga' => 'Lau', 'state' => 34, 'added_by' => 1],
            ['lga' => 'Sunkani', 'state' => 34, 'added_by' => 1],
            ['lga' => 'Takum', 'state' => 34, 'added_by' => 1],
            ['lga' => 'Ussa', 'state' => 34, 'added_by' => 1],
            ['lga' => 'Wukari', 'state' => 34, 'added_by' => 1],
            ['lga' => 'Jalingo', 'state' => 34, 'added_by' => 1],
            ['lga' => 'Karim Lamido', 'state' => 34, 'added_by' => 1],
            ['lga' => 'Nguroje', 'state' => 34, 'added_by' => 1],
            ['lga' => 'Sardauna', 'state' => 34, 'added_by' => 1],
            ['lga' => 'Yorro', 'state' => 34, 'added_by' => 1],
            ['lga' => 'Zing', 'state' => 34, 'added_by' => 1],

            ['lga' => 'Bade', 'state' => 35, 'added_by' => 1],
            ['lga' => 'Bursari', 'state' => 35, 'added_by' => 1],
            ['lga' => 'Damaturu', 'state' => 35, 'added_by' => 1],
            ['lga' => 'Fika', 'state' => 35, 'added_by' => 1],
            ['lga' => 'Fune', 'state' => 35, 'added_by' => 1],
            ['lga' => 'Gujba', 'state' => 35, 'added_by' => 1],
            ['lga' => 'Jakusko', 'state' => 35, 'added_by' => 1],
            ['lga' => 'Karasuwa', 'state' => 35, 'added_by' => 1],
            ['lga' => 'Machina', 'state' => 35, 'added_by' => 1],
            ['lga' => 'Nangere', 'state' => 35, 'added_by' => 1],
            ['lga' => 'Potiskum', 'state' => 35, 'added_by' => 1],
            ['lga' => 'Tarmuwa', 'state' => 35, 'added_by' => 1],
            ['lga' => 'Yunusari', 'state' => 35, 'added_by' => 1],
            ['lga' => 'Gashua', 'state' => 35, 'added_by' => 1],
            ['lga' => 'Nguru', 'state' => 35, 'added_by' => 1],
            ['lga' => 'Yusufari', 'state' => 35, 'added_by' => 1],

            ['lga' => 'Anka', 'state' => 36, 'added_by' => 1],
            ['lga' => 'Bakura', 'state' => 36, 'added_by' => 1],
            ['lga' => 'Bukkuyum', 'state' => 36, 'added_by' => 1],
            ['lga' => 'Bungudu', 'state' => 36, 'added_by' => 1],
            ['lga' => 'Gummi', 'state' => 36, 'added_by' => 1],
            ['lga' => 'Gusau', 'state' => 36, 'added_by' => 1],
            ['lga' => 'Kaura Namoda', 'state' => 36, 'added_by' => 1],
            ['lga' => 'Maradun', 'state' => 36, 'added_by' => 1],
            ['lga' => 'Moroa', 'state' => 36, 'added_by' => 1],
            ['lga' => 'Shinkafi', 'state' => 36, 'added_by' => 1],
            ['lga' => 'Talata Mafara', 'state' => 36, 'added_by' => 1],
            ['lga' => 'Tsafe', 'state' => 36, 'added_by' => 1],

            ['lga' => 'Abuja Municipal Area Council', 'state' => 37, 'added_by' => 1],
            ['lga' => 'Bwari', 'state' => 37, 'added_by' => 1],
            ['lga' => 'Gwagwalada', 'state' => 37, 'added_by' => 1],
            ['lga' => 'Kuje', 'state' => 37, 'added_by' => 1],
            ['lga' => 'Kwali', 'state' => 37, 'added_by' => 1],
            ['lga' => 'Abaji', 'state' => 37, 'added_by' => 1],

        ];

        DB::table('local_government_areas')->insert($lgas);
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
